# qsys scripting (.tcl) file for hollywood_hash
package require -exact qsys 16.0

create_system {hollywood_hash}

set_project_property DEVICE_FAMILY {MAX 10}
set_project_property DEVICE {10M50DAF484C6GES}
set_project_property HIDE_FROM_IP_CATALOG {false}

# Instances and instance parameters
# (disabled instances are intentionally culled)
add_instance clk_50 altera_clock_bridge 16.0
set_instance_parameter_value clk_50 {EXPLICIT_CLOCK_RATE} {50.0}
set_instance_parameter_value clk_50 {NUM_CLOCK_OUTPUTS} {1}

add_instance jtag_uart altera_avalon_jtag_uart 16.0
set_instance_parameter_value jtag_uart {allowMultipleConnections} {0}
set_instance_parameter_value jtag_uart {hubInstanceID} {0}
set_instance_parameter_value jtag_uart {readBufferDepth} {64}
set_instance_parameter_value jtag_uart {readIRQThreshold} {8}
set_instance_parameter_value jtag_uart {simInputCharacterStream} {}
set_instance_parameter_value jtag_uart {simInteractiveOptions} {INTERACTIVE_ASCII_OUTPUT}
set_instance_parameter_value jtag_uart {useRegistersForReadBuffer} {0}
set_instance_parameter_value jtag_uart {useRegistersForWriteBuffer} {0}
set_instance_parameter_value jtag_uart {useRelativePathForSimFile} {0}
set_instance_parameter_value jtag_uart {writeBufferDepth} {64}
set_instance_parameter_value jtag_uart {writeIRQThreshold} {8}

add_instance leds altera_avalon_pio 16.0
set_instance_parameter_value leds {bitClearingEdgeCapReg} {0}
set_instance_parameter_value leds {bitModifyingOutReg} {0}
set_instance_parameter_value leds {captureEdge} {0}
set_instance_parameter_value leds {direction} {Output}
set_instance_parameter_value leds {edgeType} {RISING}
set_instance_parameter_value leds {generateIRQ} {0}
set_instance_parameter_value leds {irqType} {LEVEL}
set_instance_parameter_value leds {resetValue} {0.0}
set_instance_parameter_value leds {simDoTestBenchWiring} {0}
set_instance_parameter_value leds {simDrivenValue} {0.0}
set_instance_parameter_value leds {width} {5}

add_instance mem altera_avalon_onchip_memory2 16.0
set_instance_parameter_value mem {allowInSystemMemoryContentEditor} {0}
set_instance_parameter_value mem {blockType} {AUTO}
set_instance_parameter_value mem {dataWidth} {32}
set_instance_parameter_value mem {dataWidth2} {32}
set_instance_parameter_value mem {dualPort} {0}
set_instance_parameter_value mem {enableDiffWidth} {0}
set_instance_parameter_value mem {initMemContent} {1}
set_instance_parameter_value mem {initializationFileName} {onchip_mem.hex}
set_instance_parameter_value mem {instanceID} {NONE}
set_instance_parameter_value mem {memorySize} {65536.0}
set_instance_parameter_value mem {readDuringWriteMode} {DONT_CARE}
set_instance_parameter_value mem {simAllowMRAMContentsFile} {0}
set_instance_parameter_value mem {simMemInitOnlyFilename} {0}
set_instance_parameter_value mem {singleClockOperation} {0}
set_instance_parameter_value mem {slave1Latency} {1}
set_instance_parameter_value mem {slave2Latency} {1}
set_instance_parameter_value mem {useNonDefaultInitFile} {0}
set_instance_parameter_value mem {copyInitFile} {0}
set_instance_parameter_value mem {useShallowMemBlocks} {0}
set_instance_parameter_value mem {writable} {1}
set_instance_parameter_value mem {ecc_enabled} {0}
set_instance_parameter_value mem {resetrequest_enabled} {1}

add_instance nios2 altera_nios2_gen2 16.0
set_instance_parameter_value nios2 {tmr_enabled} {0}
set_instance_parameter_value nios2 {setting_disable_tmr_inj} {0}
set_instance_parameter_value nios2 {setting_showUnpublishedSettings} {0}
set_instance_parameter_value nios2 {setting_showInternalSettings} {0}
set_instance_parameter_value nios2 {setting_preciseIllegalMemAccessException} {0}
set_instance_parameter_value nios2 {setting_exportPCB} {0}
set_instance_parameter_value nios2 {setting_exportdebuginfo} {0}
set_instance_parameter_value nios2 {setting_clearXBitsLDNonBypass} {1}
set_instance_parameter_value nios2 {setting_bigEndian} {0}
set_instance_parameter_value nios2 {setting_export_large_RAMs} {0}
set_instance_parameter_value nios2 {setting_asic_enabled} {0}
set_instance_parameter_value nios2 {setting_asic_synopsys_translate_on_off} {0}
set_instance_parameter_value nios2 {setting_asic_third_party_synthesis} {0}
set_instance_parameter_value nios2 {setting_asic_add_scan_mode_input} {0}
set_instance_parameter_value nios2 {setting_oci_version} {1}
set_instance_parameter_value nios2 {setting_fast_register_read} {0}
set_instance_parameter_value nios2 {setting_exportHostDebugPort} {0}
set_instance_parameter_value nios2 {setting_oci_export_jtag_signals} {0}
set_instance_parameter_value nios2 {setting_avalonDebugPortPresent} {0}
set_instance_parameter_value nios2 {setting_alwaysEncrypt} {1}
set_instance_parameter_value nios2 {io_regionbase} {0}
set_instance_parameter_value nios2 {io_regionsize} {0}
set_instance_parameter_value nios2 {setting_support31bitdcachebypass} {1}
set_instance_parameter_value nios2 {setting_activateTrace} {0}
set_instance_parameter_value nios2 {setting_allow_break_inst} {0}
set_instance_parameter_value nios2 {setting_activateTestEndChecker} {0}
set_instance_parameter_value nios2 {setting_ecc_sim_test_ports} {0}
set_instance_parameter_value nios2 {setting_disableocitrace} {0}
set_instance_parameter_value nios2 {setting_activateMonitors} {1}
set_instance_parameter_value nios2 {setting_HDLSimCachesCleared} {1}
set_instance_parameter_value nios2 {setting_HBreakTest} {0}
set_instance_parameter_value nios2 {setting_breakslaveoveride} {0}
set_instance_parameter_value nios2 {mpu_useLimit} {0}
set_instance_parameter_value nios2 {mpu_enabled} {0}
set_instance_parameter_value nios2 {mmu_enabled} {0}
set_instance_parameter_value nios2 {mmu_autoAssignTlbPtrSz} {1}
set_instance_parameter_value nios2 {cpuReset} {0}
set_instance_parameter_value nios2 {resetrequest_enabled} {1}
set_instance_parameter_value nios2 {setting_removeRAMinit} {0}
set_instance_parameter_value nios2 {setting_tmr_output_disable} {0}
set_instance_parameter_value nios2 {setting_shadowRegisterSets} {0}
set_instance_parameter_value nios2 {mpu_numOfInstRegion} {8}
set_instance_parameter_value nios2 {mpu_numOfDataRegion} {8}
set_instance_parameter_value nios2 {mmu_TLBMissExcOffset} {0}
set_instance_parameter_value nios2 {resetOffset} {0}
set_instance_parameter_value nios2 {exceptionOffset} {32}
set_instance_parameter_value nios2 {cpuID} {0}
set_instance_parameter_value nios2 {breakOffset} {32}
set_instance_parameter_value nios2 {userDefinedSettings} {}
set_instance_parameter_value nios2 {tracefilename} {}
set_instance_parameter_value nios2 {resetSlave} {mem.s1}
set_instance_parameter_value nios2 {mmu_TLBMissExcSlave} {None}
set_instance_parameter_value nios2 {exceptionSlave} {mem.s1}
set_instance_parameter_value nios2 {breakSlave} {mem.s1}
set_instance_parameter_value nios2 {setting_interruptControllerType} {Internal}
set_instance_parameter_value nios2 {setting_branchpredictiontype} {Dynamic}
set_instance_parameter_value nios2 {setting_bhtPtrSz} {8}
set_instance_parameter_value nios2 {cpuArchRev} {1}
set_instance_parameter_value nios2 {mul_shift_choice} {0}
set_instance_parameter_value nios2 {mul_32_impl} {2}
set_instance_parameter_value nios2 {mul_64_impl} {1}
set_instance_parameter_value nios2 {shift_rot_impl} {1}
set_instance_parameter_value nios2 {dividerType} {srt2}
set_instance_parameter_value nios2 {mpu_minInstRegionSize} {12}
set_instance_parameter_value nios2 {mpu_minDataRegionSize} {12}
set_instance_parameter_value nios2 {mmu_uitlbNumEntries} {4}
set_instance_parameter_value nios2 {mmu_udtlbNumEntries} {6}
set_instance_parameter_value nios2 {mmu_tlbPtrSz} {7}
set_instance_parameter_value nios2 {mmu_tlbNumWays} {16}
set_instance_parameter_value nios2 {mmu_processIDNumBits} {8}
set_instance_parameter_value nios2 {impl} {Tiny}
set_instance_parameter_value nios2 {icache_size} {16384}
set_instance_parameter_value nios2 {fa_cache_line} {2}
set_instance_parameter_value nios2 {fa_cache_linesize} {0}
set_instance_parameter_value nios2 {icache_tagramBlockType} {Automatic}
set_instance_parameter_value nios2 {icache_ramBlockType} {Automatic}
set_instance_parameter_value nios2 {icache_numTCIM} {0}
set_instance_parameter_value nios2 {icache_burstType} {Sequential}
set_instance_parameter_value nios2 {dcache_bursts} {true}
set_instance_parameter_value nios2 {dcache_victim_buf_impl} {ram}
set_instance_parameter_value nios2 {dcache_size} {4096}
set_instance_parameter_value nios2 {dcache_tagramBlockType} {Automatic}
set_instance_parameter_value nios2 {dcache_ramBlockType} {Automatic}
set_instance_parameter_value nios2 {dcache_numTCDM} {0}
set_instance_parameter_value nios2 {setting_exportvectors} {0}
set_instance_parameter_value nios2 {setting_usedesignware} {0}
set_instance_parameter_value nios2 {setting_ecc_present} {0}
set_instance_parameter_value nios2 {setting_ic_ecc_present} {1}
set_instance_parameter_value nios2 {setting_rf_ecc_present} {1}
set_instance_parameter_value nios2 {setting_mmu_ecc_present} {1}
set_instance_parameter_value nios2 {setting_dc_ecc_present} {1}
set_instance_parameter_value nios2 {setting_itcm_ecc_present} {1}
set_instance_parameter_value nios2 {setting_dtcm_ecc_present} {1}
set_instance_parameter_value nios2 {regfile_ramBlockType} {Automatic}
set_instance_parameter_value nios2 {ocimem_ramBlockType} {Automatic}
set_instance_parameter_value nios2 {ocimem_ramInit} {0}
set_instance_parameter_value nios2 {mmu_ramBlockType} {Automatic}
set_instance_parameter_value nios2 {bht_ramBlockType} {Automatic}
set_instance_parameter_value nios2 {cdx_enabled} {0}
set_instance_parameter_value nios2 {mpx_enabled} {0}
set_instance_parameter_value nios2 {debug_enabled} {1}
set_instance_parameter_value nios2 {debug_triggerArming} {1}
set_instance_parameter_value nios2 {debug_debugReqSignals} {0}
set_instance_parameter_value nios2 {debug_assignJtagInstanceID} {0}
set_instance_parameter_value nios2 {debug_jtagInstanceID} {0}
set_instance_parameter_value nios2 {debug_OCIOnchipTrace} {_128}
set_instance_parameter_value nios2 {debug_hwbreakpoint} {0}
set_instance_parameter_value nios2 {debug_datatrigger} {0}
set_instance_parameter_value nios2 {debug_traceType} {none}
set_instance_parameter_value nios2 {debug_traceStorage} {onchip_trace}
set_instance_parameter_value nios2 {master_addr_map} {0}
set_instance_parameter_value nios2 {instruction_master_paddr_base} {0}
set_instance_parameter_value nios2 {instruction_master_paddr_size} {0.0}
set_instance_parameter_value nios2 {flash_instruction_master_paddr_base} {0}
set_instance_parameter_value nios2 {flash_instruction_master_paddr_size} {0.0}
set_instance_parameter_value nios2 {data_master_paddr_base} {0}
set_instance_parameter_value nios2 {data_master_paddr_size} {0.0}
set_instance_parameter_value nios2 {tightly_coupled_instruction_master_0_paddr_base} {0}
set_instance_parameter_value nios2 {tightly_coupled_instruction_master_0_paddr_size} {0.0}
set_instance_parameter_value nios2 {tightly_coupled_instruction_master_1_paddr_base} {0}
set_instance_parameter_value nios2 {tightly_coupled_instruction_master_1_paddr_size} {0.0}
set_instance_parameter_value nios2 {tightly_coupled_instruction_master_2_paddr_base} {0}
set_instance_parameter_value nios2 {tightly_coupled_instruction_master_2_paddr_size} {0.0}
set_instance_parameter_value nios2 {tightly_coupled_instruction_master_3_paddr_base} {0}
set_instance_parameter_value nios2 {tightly_coupled_instruction_master_3_paddr_size} {0.0}
set_instance_parameter_value nios2 {tightly_coupled_data_master_0_paddr_base} {0}
set_instance_parameter_value nios2 {tightly_coupled_data_master_0_paddr_size} {0.0}
set_instance_parameter_value nios2 {tightly_coupled_data_master_1_paddr_base} {0}
set_instance_parameter_value nios2 {tightly_coupled_data_master_1_paddr_size} {0.0}
set_instance_parameter_value nios2 {tightly_coupled_data_master_2_paddr_base} {0}
set_instance_parameter_value nios2 {tightly_coupled_data_master_2_paddr_size} {0.0}
set_instance_parameter_value nios2 {tightly_coupled_data_master_3_paddr_base} {0}
set_instance_parameter_value nios2 {tightly_coupled_data_master_3_paddr_size} {0.0}
set_instance_parameter_value nios2 {instruction_master_high_performance_paddr_base} {0}
set_instance_parameter_value nios2 {instruction_master_high_performance_paddr_size} {0.0}
set_instance_parameter_value nios2 {data_master_high_performance_paddr_base} {0}
set_instance_parameter_value nios2 {data_master_high_performance_paddr_size} {0.0}

add_instance pll altpll 16.0
set_instance_parameter_value pll {HIDDEN_CUSTOM_ELABORATION} {altpll_avalon_elaboration}
set_instance_parameter_value pll {HIDDEN_CUSTOM_POST_EDIT} {altpll_avalon_post_edit}
set_instance_parameter_value pll {INTENDED_DEVICE_FAMILY} {MAX 10}
set_instance_parameter_value pll {WIDTH_CLOCK} {5}
set_instance_parameter_value pll {WIDTH_PHASECOUNTERSELECT} {}
set_instance_parameter_value pll {PRIMARY_CLOCK} {}
set_instance_parameter_value pll {INCLK0_INPUT_FREQUENCY} {20000}
set_instance_parameter_value pll {INCLK1_INPUT_FREQUENCY} {}
set_instance_parameter_value pll {OPERATION_MODE} {NORMAL}
set_instance_parameter_value pll {PLL_TYPE} {AUTO}
set_instance_parameter_value pll {QUALIFY_CONF_DONE} {}
set_instance_parameter_value pll {COMPENSATE_CLOCK} {CLK0}
set_instance_parameter_value pll {SCAN_CHAIN} {}
set_instance_parameter_value pll {GATE_LOCK_SIGNAL} {}
set_instance_parameter_value pll {GATE_LOCK_COUNTER} {}
set_instance_parameter_value pll {LOCK_HIGH} {}
set_instance_parameter_value pll {LOCK_LOW} {}
set_instance_parameter_value pll {VALID_LOCK_MULTIPLIER} {}
set_instance_parameter_value pll {INVALID_LOCK_MULTIPLIER} {}
set_instance_parameter_value pll {SWITCH_OVER_ON_LOSSCLK} {}
set_instance_parameter_value pll {SWITCH_OVER_ON_GATED_LOCK} {}
set_instance_parameter_value pll {ENABLE_SWITCH_OVER_COUNTER} {}
set_instance_parameter_value pll {SKIP_VCO} {}
set_instance_parameter_value pll {SWITCH_OVER_COUNTER} {}
set_instance_parameter_value pll {SWITCH_OVER_TYPE} {}
set_instance_parameter_value pll {FEEDBACK_SOURCE} {}
set_instance_parameter_value pll {BANDWIDTH} {}
set_instance_parameter_value pll {BANDWIDTH_TYPE} {AUTO}
set_instance_parameter_value pll {SPREAD_FREQUENCY} {}
set_instance_parameter_value pll {DOWN_SPREAD} {}
set_instance_parameter_value pll {SELF_RESET_ON_GATED_LOSS_LOCK} {}
set_instance_parameter_value pll {SELF_RESET_ON_LOSS_LOCK} {}
set_instance_parameter_value pll {CLK0_MULTIPLY_BY} {1}
set_instance_parameter_value pll {CLK1_MULTIPLY_BY} {1}
set_instance_parameter_value pll {CLK2_MULTIPLY_BY} {1}
set_instance_parameter_value pll {CLK3_MULTIPLY_BY} {6}
set_instance_parameter_value pll {CLK4_MULTIPLY_BY} {2}
set_instance_parameter_value pll {CLK5_MULTIPLY_BY} {}
set_instance_parameter_value pll {CLK6_MULTIPLY_BY} {}
set_instance_parameter_value pll {CLK7_MULTIPLY_BY} {}
set_instance_parameter_value pll {CLK8_MULTIPLY_BY} {}
set_instance_parameter_value pll {CLK9_MULTIPLY_BY} {}
set_instance_parameter_value pll {EXTCLK0_MULTIPLY_BY} {}
set_instance_parameter_value pll {EXTCLK1_MULTIPLY_BY} {}
set_instance_parameter_value pll {EXTCLK2_MULTIPLY_BY} {}
set_instance_parameter_value pll {EXTCLK3_MULTIPLY_BY} {}
set_instance_parameter_value pll {CLK0_DIVIDE_BY} {5}
set_instance_parameter_value pll {CLK1_DIVIDE_BY} {1}
set_instance_parameter_value pll {CLK2_DIVIDE_BY} {1}
set_instance_parameter_value pll {CLK3_DIVIDE_BY} {1}
set_instance_parameter_value pll {CLK4_DIVIDE_BY} {5}
set_instance_parameter_value pll {CLK5_DIVIDE_BY} {}
set_instance_parameter_value pll {CLK6_DIVIDE_BY} {}
set_instance_parameter_value pll {CLK7_DIVIDE_BY} {}
set_instance_parameter_value pll {CLK8_DIVIDE_BY} {}
set_instance_parameter_value pll {CLK9_DIVIDE_BY} {}
set_instance_parameter_value pll {EXTCLK0_DIVIDE_BY} {}
set_instance_parameter_value pll {EXTCLK1_DIVIDE_BY} {}
set_instance_parameter_value pll {EXTCLK2_DIVIDE_BY} {}
set_instance_parameter_value pll {EXTCLK3_DIVIDE_BY} {}
set_instance_parameter_value pll {CLK0_PHASE_SHIFT} {0}
set_instance_parameter_value pll {CLK1_PHASE_SHIFT} {0}
set_instance_parameter_value pll {CLK2_PHASE_SHIFT} {0}
set_instance_parameter_value pll {CLK3_PHASE_SHIFT} {0}
set_instance_parameter_value pll {CLK4_PHASE_SHIFT} {5000}
set_instance_parameter_value pll {CLK5_PHASE_SHIFT} {}
set_instance_parameter_value pll {CLK6_PHASE_SHIFT} {}
set_instance_parameter_value pll {CLK7_PHASE_SHIFT} {}
set_instance_parameter_value pll {CLK8_PHASE_SHIFT} {}
set_instance_parameter_value pll {CLK9_PHASE_SHIFT} {}
set_instance_parameter_value pll {EXTCLK0_PHASE_SHIFT} {}
set_instance_parameter_value pll {EXTCLK1_PHASE_SHIFT} {}
set_instance_parameter_value pll {EXTCLK2_PHASE_SHIFT} {}
set_instance_parameter_value pll {EXTCLK3_PHASE_SHIFT} {}
set_instance_parameter_value pll {CLK0_DUTY_CYCLE} {50}
set_instance_parameter_value pll {CLK1_DUTY_CYCLE} {50}
set_instance_parameter_value pll {CLK2_DUTY_CYCLE} {50}
set_instance_parameter_value pll {CLK3_DUTY_CYCLE} {50}
set_instance_parameter_value pll {CLK4_DUTY_CYCLE} {50}
set_instance_parameter_value pll {CLK5_DUTY_CYCLE} {}
set_instance_parameter_value pll {CLK6_DUTY_CYCLE} {}
set_instance_parameter_value pll {CLK7_DUTY_CYCLE} {}
set_instance_parameter_value pll {CLK8_DUTY_CYCLE} {}
set_instance_parameter_value pll {CLK9_DUTY_CYCLE} {}
set_instance_parameter_value pll {EXTCLK0_DUTY_CYCLE} {}
set_instance_parameter_value pll {EXTCLK1_DUTY_CYCLE} {}
set_instance_parameter_value pll {EXTCLK2_DUTY_CYCLE} {}
set_instance_parameter_value pll {EXTCLK3_DUTY_CYCLE} {}
set_instance_parameter_value pll {PORT_clkena0} {PORT_UNUSED}
set_instance_parameter_value pll {PORT_clkena1} {PORT_UNUSED}
set_instance_parameter_value pll {PORT_clkena2} {PORT_UNUSED}
set_instance_parameter_value pll {PORT_clkena3} {PORT_UNUSED}
set_instance_parameter_value pll {PORT_clkena4} {PORT_UNUSED}
set_instance_parameter_value pll {PORT_clkena5} {PORT_UNUSED}
set_instance_parameter_value pll {PORT_extclkena0} {}
set_instance_parameter_value pll {PORT_extclkena1} {}
set_instance_parameter_value pll {PORT_extclkena2} {}
set_instance_parameter_value pll {PORT_extclkena3} {}
set_instance_parameter_value pll {PORT_extclk0} {PORT_UNUSED}
set_instance_parameter_value pll {PORT_extclk1} {PORT_UNUSED}
set_instance_parameter_value pll {PORT_extclk2} {PORT_UNUSED}
set_instance_parameter_value pll {PORT_extclk3} {PORT_UNUSED}
set_instance_parameter_value pll {PORT_CLKBAD0} {PORT_UNUSED}
set_instance_parameter_value pll {PORT_CLKBAD1} {PORT_UNUSED}
set_instance_parameter_value pll {PORT_clk0} {PORT_USED}
set_instance_parameter_value pll {PORT_clk1} {PORT_USED}
set_instance_parameter_value pll {PORT_clk2} {PORT_USED}
set_instance_parameter_value pll {PORT_clk3} {PORT_USED}
set_instance_parameter_value pll {PORT_clk4} {PORT_USED}
set_instance_parameter_value pll {PORT_clk5} {PORT_UNUSED}
set_instance_parameter_value pll {PORT_clk6} {}
set_instance_parameter_value pll {PORT_clk7} {}
set_instance_parameter_value pll {PORT_clk8} {}
set_instance_parameter_value pll {PORT_clk9} {}
set_instance_parameter_value pll {PORT_SCANDATA} {PORT_UNUSED}
set_instance_parameter_value pll {PORT_SCANDATAOUT} {PORT_UNUSED}
set_instance_parameter_value pll {PORT_SCANDONE} {PORT_UNUSED}
set_instance_parameter_value pll {PORT_SCLKOUT1} {}
set_instance_parameter_value pll {PORT_SCLKOUT0} {}
set_instance_parameter_value pll {PORT_ACTIVECLOCK} {PORT_UNUSED}
set_instance_parameter_value pll {PORT_CLKLOSS} {PORT_UNUSED}
set_instance_parameter_value pll {PORT_INCLK1} {PORT_UNUSED}
set_instance_parameter_value pll {PORT_INCLK0} {PORT_USED}
set_instance_parameter_value pll {PORT_FBIN} {PORT_UNUSED}
set_instance_parameter_value pll {PORT_PLLENA} {PORT_UNUSED}
set_instance_parameter_value pll {PORT_CLKSWITCH} {PORT_UNUSED}
set_instance_parameter_value pll {PORT_ARESET} {PORT_USED}
set_instance_parameter_value pll {PORT_PFDENA} {PORT_UNUSED}
set_instance_parameter_value pll {PORT_SCANCLK} {PORT_UNUSED}
set_instance_parameter_value pll {PORT_SCANACLR} {PORT_UNUSED}
set_instance_parameter_value pll {PORT_SCANREAD} {PORT_UNUSED}
set_instance_parameter_value pll {PORT_SCANWRITE} {PORT_UNUSED}
set_instance_parameter_value pll {PORT_ENABLE0} {}
set_instance_parameter_value pll {PORT_ENABLE1} {}
set_instance_parameter_value pll {PORT_LOCKED} {PORT_USED}
set_instance_parameter_value pll {PORT_CONFIGUPDATE} {PORT_UNUSED}
set_instance_parameter_value pll {PORT_FBOUT} {}
set_instance_parameter_value pll {PORT_PHASEDONE} {PORT_UNUSED}
set_instance_parameter_value pll {PORT_PHASESTEP} {PORT_UNUSED}
set_instance_parameter_value pll {PORT_PHASEUPDOWN} {PORT_UNUSED}
set_instance_parameter_value pll {PORT_SCANCLKENA} {PORT_UNUSED}
set_instance_parameter_value pll {PORT_PHASECOUNTERSELECT} {PORT_UNUSED}
set_instance_parameter_value pll {PORT_VCOOVERRANGE} {}
set_instance_parameter_value pll {PORT_VCOUNDERRANGE} {}
set_instance_parameter_value pll {DPA_MULTIPLY_BY} {}
set_instance_parameter_value pll {DPA_DIVIDE_BY} {}
set_instance_parameter_value pll {DPA_DIVIDER} {}
set_instance_parameter_value pll {VCO_MULTIPLY_BY} {}
set_instance_parameter_value pll {VCO_DIVIDE_BY} {}
set_instance_parameter_value pll {SCLKOUT0_PHASE_SHIFT} {}
set_instance_parameter_value pll {SCLKOUT1_PHASE_SHIFT} {}
set_instance_parameter_value pll {VCO_FREQUENCY_CONTROL} {}
set_instance_parameter_value pll {VCO_PHASE_SHIFT_STEP} {}
set_instance_parameter_value pll {USING_FBMIMICBIDIR_PORT} {}
set_instance_parameter_value pll {SCAN_CHAIN_MIF_FILE} {}
set_instance_parameter_value pll {AVALON_USE_SEPARATE_SYSCLK} {NO}

