# TCL File Generated by Component Editor 16.0
# Fri Aug 12 22:41:09 PDT 2016
# DO NOT MODIFY


# 
# hollywood_hash_core "hollywood_hash_core" v1.0
#  2016.08.12.22:41:09
# 
# 

# 
# request TCL package from ACDS 16.0
# 
package require -exact qsys 16.0


# 
# module hollywood_hash_core
# 
set_module_property DESCRIPTION ""
set_module_property NAME hollywood_hash_core
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME hollywood_hash_core
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL hollywood_unhash_core
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file hollywood_hash_core.sv SYSTEM_VERILOG PATH hollywood_hash_core.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL hollywood_unhash_core
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file hollywood_hash_core.sv SYSTEM_VERILOG PATH hollywood_hash_core.sv


# 
# parameters
# 
add_parameter R4 STD_LOGIC_VECTOR 65201
set_parameter_property R4 DEFAULT_VALUE 65201
set_parameter_property R4 DISPLAY_NAME R4
set_parameter_property R4 TYPE STD_LOGIC_VECTOR
set_parameter_property R4 UNITS None
set_parameter_property R4 ALLOWED_RANGES 0:262143
set_parameter_property R4 HDL_PARAMETER true
add_parameter R6 STD_LOGIC_VECTOR 37528
set_parameter_property R6 DEFAULT_VALUE 37528
set_parameter_property R6 DISPLAY_NAME R6
set_parameter_property R6 TYPE STD_LOGIC_VECTOR
set_parameter_property R6 UNITS None
set_parameter_property R6 ALLOWED_RANGES 0:262143
set_parameter_property R6 HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point mgmt
# 
add_interface mgmt avalon_streaming end
set_interface_property mgmt associatedClock clock
set_interface_property mgmt dataBitsPerSymbol 8
set_interface_property mgmt errorDescriptor ""
set_interface_property mgmt firstSymbolInHighOrderBits true
set_interface_property mgmt maxChannel 0
set_interface_property mgmt readyLatency 0
set_interface_property mgmt ENABLED true
set_interface_property mgmt EXPORT_OF ""
set_interface_property mgmt PORT_NAME_MAP ""
set_interface_property mgmt CMSIS_SVD_VARIABLES ""
set_interface_property mgmt SVD_ADDRESS_GROUP ""

add_interface_port mgmt mgmt_data data Input 8
add_interface_port mgmt mgmt_valid valid Input 1


# 
# connection point in
# 
add_interface in avalon_streaming end
set_interface_property in associatedClock clock
set_interface_property in dataBitsPerSymbol 8
set_interface_property in errorDescriptor ""
set_interface_property in firstSymbolInHighOrderBits true
set_interface_property in maxChannel 0
set_interface_property in readyLatency 0
set_interface_property in ENABLED true
set_interface_property in EXPORT_OF ""
set_interface_property in PORT_NAME_MAP ""
set_interface_property in CMSIS_SVD_VARIABLES ""
set_interface_property in SVD_ADDRESS_GROUP ""

add_interface_port in in_data data Input 16
add_interface_port in in_valid valid Input 1


# 
# connection point out
# 
add_interface out avalon_streaming start
set_interface_property out associatedClock clock
set_interface_property out dataBitsPerSymbol 8
set_interface_property out errorDescriptor ""
set_interface_property out firstSymbolInHighOrderBits true
set_interface_property out maxChannel 0
set_interface_property out readyLatency 0
set_interface_property out ENABLED true
set_interface_property out EXPORT_OF ""
set_interface_property out PORT_NAME_MAP ""
set_interface_property out CMSIS_SVD_VARIABLES ""
set_interface_property out SVD_ADDRESS_GROUP ""

add_interface_port out out_data data Output 16
add_interface_port out out_valid valid Output 1

